version: "3.7"
services:
  client:
    restart: unless-stopped
    container_name: trye_portfolio
    build:
      context: ./Client
      dockerfile: Dockerfile

    networks:
      - frontend_network

    environment:
      - CHOKIDAR_USEPOLLING=true

    ports:
      - "3000:3000"
    volumes:
      - client-static:/usr/share/nginx/html

    # depends_on:
    #   - backend

  server:
    restart: unless-stopped
    container_name: trye_server
    build:
      context: ./Server
      dockerfile: Dockerfile

    ports:
      - "5000:5000"
    volumes:
      - client-static:/api/dist
    networks:
      - backend_network
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - client # Add the client service as a dependency
networks:
  frontend_network:
  backend_network:

volumes:
  client-static:
